import { stages, href } from './exhibition-content.js';
import { renderResearch } from './research.js';
import { setupGalleryFrame } from './gallery-frame.js';
const root=document.body.dataset.root||'.';
const index=stages.findIndex(s=>s.id===document.body.dataset.chapter);
function typefield(word) {return `<div class="exhibition-typefield" aria-hidden="true"><span>${word}</span><span>${word}</span></div>`;}
function home() {
  document.querySelector('[data-home-content]').innerHTML=`<section class="heal-hero">${typefield('HARM / EXHAUST / ADAPT / LIVEN')}<div class="heal-hero__meta section-label"><span>SPEC 1 / COMM2754 / GROUP EXHIBITION</span><span>DAMAGE TO RECOVERY</span></div><h1 aria-label="HEAL"><span>H</span><span>E</span><span>A</span><span>L</span></h1><div class="heal-hero__bottom"><div><h2>One connected journey from damage to recovery.</h2><p>Four interactive generative artworks explore how energy choices shape environmental change, from fossil-fuel damage toward renewable-energy recovery.</p></div><a class="primary-link" href="${href(root,stages[0])}">BEGIN THE JOURNEY <span aria-hidden="true">→</span></a></div></section><nav class="stage-preview heal-preview" aria-label="HARM to LIVEN: four connected chapters">${stages.map(s=>`<a class="preview--${s.id}" href="${href(root,s)}"><span class="section-label">${s.number} / ${s.role}</span><strong>${s.title}<i aria-hidden="true">→</i></strong><span>${s.subtitle}</span></a>`).join('')}</nav><div class="landing-end"><span class="section-label">CAUSE → CONSEQUENCE → RESPONSE → RECOVERY</span><a class="text-link" href="${href(root,stages[0])}">ENTER HARM →</a></div>`;
}
function stage() {
 const s=stages[index],previous=index?href(root,stages[index-1]):`${root}/index.html`,next=index<3?href(root,stages[index+1]):`${root}/about.html`;
 const host=document.querySelector('[data-artwork-content]');
 host.innerHTML=`${typefield(s.title)}<section class="gallery-panel" aria-labelledby="artwork-heading"><header class="gallery-heading"><div class="gallery-identity"><span class="section-label">${s.number} / 04 · ${s.role.toUpperCase()}</span><h1 id="artwork-heading">${s.title}</h1></div><div class="gallery-context"><h2>${s.heading}</h2><p>${s.description}</p></div></header><div class="gallery-frame" data-gallery-frame aria-busy="true"><iframe title="${s.title} — interactive artwork by ${s.artist}" aria-describedby="interaction-help" allow="fullscreen" allowfullscreen data-gallery-iframe></iframe><div class="gallery-loading" role="status" data-gallery-loading><span class="section-label">${s.number} / 04</span><strong>${s.title}</strong><p>Preparing the artwork…</p></div><div class="gallery-error" data-gallery-error hidden><h2>The artwork could not load.</h2><button type="button" data-gallery-retry>RETRY ↻</button><a href="${root}/artworks/${s.id}/index.html">OPEN ARTWORK DIRECTLY ↗</a></div></div><div class="gallery-tools"><p id="interaction-help"><span class="section-label">INTERACT</span>${s.instruction}</p><div class="gallery-controls" role="group" aria-label="${s.title} artwork controls"><button type="button" data-gallery-mute disabled aria-pressed="false">SOUND ON</button><button type="button" data-gallery-mix disabled>SOUND MIX</button><button type="button" data-gallery-reset disabled>RESET ↻</button><button type="button" data-gallery-fullscreen>FULLSCREEN ↗</button></div></div></section><aside class="journey-complete" data-journey-complete hidden role="status"><div><span class="section-label">YOU COMPLETED THE JOURNEY</span><strong>FROM DAMAGE TO RECOVERY</strong><p>HARM → EXHAUST → ADAPT → LIVEN · One connected journey from damage to recovery.</p></div><a href="${root}/about.html">ABOUT HEAL →</a><button type="button" data-dismiss-completion aria-label="Dismiss journey conclusion">×</button></aside><nav class="exhibition-adjacent" aria-label="Previous and next chapters"><a href="${previous}" rel="prev">← ${index?stages[index-1].title:'HOME'}</a><span class="keyboard-hint">${s.number} / 04 · ${s.subtitle.toUpperCase()}<i>← → TO EXPLORE</i></span><a href="${next}" rel="next">${index<3?stages[index+1].title:'ABOUT HEAL'} →</a></nav>`;
 setupGalleryFrame(host,s,`${root}/artworks/${s.id}/index.html?gallery=heal`);
 document.addEventListener('keydown',event=>{
  if(event.defaultPrevented||event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||document.body.classList.contains('menu-is-open')||event.target.closest('input,textarea,select,button,[contenteditable],iframe')) return;
  const target=event.key==='ArrowLeft'?previous:event.key==='ArrowRight'?next:/^[1-4]$/.test(event.key)?href(root,stages[Number(event.key)-1]):null;
  if(target){event.preventDefault();location.assign(target);}
 });
}
export function renderExhibition(){if(index>=0)stage();else if(document.body.dataset.page==='home')home();else if(document.body.dataset.page==='about')renderResearch(document.querySelector('[data-about-content]'),root);}
